english_games/english_games/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('word_wolf/', include('word_wolf.urls')),
]

english_games/word_wolf/urls.py
from django.urls import path
from . import views
 
app_name = 'word_wolf'
urlpatterns = [
    path('top/', views.top_template, name='top_template'),
    path('rule/', views.rule_template, name='rule_template'),
    path('player/', views.player_template, name='player_template'),
    path('check/', views.check_template, name='check_template'),
    path('topic/', views.topic_template, name='topic_template'),
    path('start/', views.start_template, name='start_template'),
    path('time/', views.time_template, name='time_template'),
    path('finish/', views.finish_template, name='finish_template'),
    path('result/', views.result_template, name='result_template'),
    path('lang/', views.lang_template, name='lang_template'),
]

english_games/word_wolf/models.py
from django.db import models

# Create your models here.
class Genre(models.Model):
    genre_en = models.CharField(max_length=100, blank=True, null=True)


class English(models.Model):
    topic_a = models.CharField(max_length=100, blank=True, null=True)
    topic_b = models.CharField(max_length=100, blank=True, null=True)
    genre_id = models.ForeignKey(Genre, on_delete=models.PROTECT)

english_games/word_wolf/views.py
from django.shortcuts import render
from .models import English, Genre

# def lang_template(request):
#     return render(request, 'word_wolf/lang.html')

# -------共通関数-------
def get_1_or_int(request, name):
    post_value = request.POST.get(name)
    if post_value is not None:
        # request.POST.get("minority") が値を持っている場合
        value = post_value  # 必要に応じて型変換
    else:
        # request.POST.get("minority") が値を持っていない場合
        value = 1
    return value


def get_2_or_int(request, name):
    post_value = request.POST.get(name)
    if post_value is not None:
        # request.POST.get("minority") が値を持っている場合
        value = post_value  # 必要に応じて型変換
    else:
        # request.POST.get("minority") が値を持っていない場合
        value = 2
    return value


# Create your views here.
def top_template(request):
    params = {'players': get_2_or_int(request, "players"),
                'minority': get_1_or_int(request, "minority")}
    return render(request, 'word_wolf/top.html', params)


def rule_template(request):
    return render(request, 'word_wolf/rule.html')


def player_template(request):
    if request.POST.get("genre") == "":
        # genre選択されていない場合の処理
        params = {'players': get_2_or_int(request, "players"),
                    'minority': get_1_or_int(request, "minority"),
                    'message': "Please select Genere"}
        return render(request, 'word_wolf/top.html', params)
    else:
        # genreが選択されていてplayerページに遷移する場合の処理
        players_num_list = list(range(1, int(get_2_or_int(request, "players")) + 1))
        params = {'players_num_list': ["player_name" + str(item) for item in players_num_list]}
        request.session['players_num'] = get_2_or_int(request, "players")
        return render(request, 'word_wolf/player.html', params)


def check_template(request):
    request.session['player_name1'] = request.POST.get("player_name1")
    print('request.POST.get("player_name1")')
    print(request.POST.get("player_name1"))
    print('request.session[player_name1]')
    print(request.session['player_name1'])
    print("request.session['players_num']")
    print(request.session['players_num'])

    player_data = {}
    for num in range(int(request.session['players_num'])):
        key = f"player_name{num + 1}"
        player_name = request.POST.get(key)
        player_data[key] = player_name
    
    print("player_data")
    print(player_data)
    request.session['player_data'] = player_data
    return render(request, 'word_wolf/check.html')


def topic_template(request):
    return render(request, 'word_wolf/topic.html')


def lang_template(request):
    return render(request, 'word_wolf/lang.html')


def start_template(request):
    return render(request, 'word_wolf/start.html')


def time_template(request):
    return render(request, 'word_wolf/time.html')


def finish_template(request):
    return render(request, 'word_wolf/finish.html')


def result_template(request):
    return render(request, 'word_wolf/result.html')

english_games/word_wolf/templates/word_wolf/check.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- css -->
  <link rel="stylesheet" href="{% static 'word_wolf/common.css' %}">

  <!-- javascript -->
  <script src="{% static 'word_wolf/common.js' %}"></script>

  <title>英語ゲームWord Wolf</title>
</head>

<body>
  <nav class="navbar navbar-light fixed-top navbar-color">
    <div class="container-fluid">
      <a class="navbar-brand fs-3 text-light top-font" href="#">
        <img src="{% static 'word_wolf/School.png' %}" width="35" height="35" class="d-inline-block align-text-top"
          alt="word wolf">
        English Game
      </a>
    </div>
  </nav>
  <main class="equal_margin">
    <div class="space"></div>
    <img src="{% static 'word_wolf/word_wolf_none_sub.png' %}" width="150" height="150" class="equal_margin"
      alt="word wolf">
    <h2 class="text-center text-light">Are you {{ request.session.player_name1 }}？</h2>
    <h3 class="text-center orange-text">DO NOT SHOW<br>YOUR TOPIC TO OTHERS!!</h3>
    <div class="button-size2 equal_margin mt-3">
      <a class="btn btn-light rounded-pill equal_margin" href="{% url 'word_wolf:topic_template' %}"
        role="button">YES</a>
    </div>
  </main>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

english_games/word_wolf/templates/word_wolf/finish.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- css -->
  <link rel="stylesheet" href="{% static 'word_wolf/common.css' %}">

  <!-- javascript -->
  <script src="{% static 'word_wolf/common.js' %}"></script>

  <title>英語ゲームWord Wolf</title>
</head>

<body>
  <nav class="navbar navbar-light fixed-top navbar-color">
    <div class="container-fluid">
      <a class="navbar-brand fs-3 text-light top-font" href="#">
        <img src="{% static 'word_wolf/School.png' %}" width="35" height="35" class="d-inline-block align-text-top"
          alt="word wolf">
        English Game
      </a>
    </div>
  </nav>
  <main class="equal_margin">
    <div class="space"></div>
    <img src="{% static 'word_wolf/word_wolf_none_sub.png' %}" width="150" height="150" class="equal_margin"
      alt="word wolf">
    <h2 class="text-center text-light">トーク終了！！</h2>
    <div class="card card-top text-center equal_margin">
      <div class="card-body">
        <p>みんなで一斉に少数派だと思う人を指差しましょう！！</p>
        <p>いっせーのっせ！</p>
        <p>一番多く指を指された人がウルフ（少数派）だったら、村人（多数派）の勝ち。</p>
        <p>一番多く指を指された人が村人（多数派）だったら、ウルフ（少数派）の勝ちです。</p>
        <p>では答えを確認しましょう！</p>
      </div>
    </div>
    <div class="button-size2 equal_margin mt-3">
      <a class="btn btn-light rounded-pill equal_margin" href="{% url 'word_wolf:result_template' %}"
        role="button">答えを見る</a>
    </div>
  </main>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

english_games/word_wolf/templates/word_wolf/player.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- css -->
  <link rel="stylesheet" href="{% static 'word_wolf/common.css' %}">

  <!-- javascript -->
  <script src="{% static 'word_wolf/common.js' %}"></script>

  <title>英語ゲームWord Wolf</title>
</head>

<body>
  <nav class="navbar navbar-light fixed-top navbar-color">
    <div class="container-fluid">
      <a class="navbar-brand fs-3 text-light top-font" href="#">
        <img src="{% static 'word_wolf/School.png' %}" width="35" height="35" class="d-inline-block align-text-top"
          alt="word wolf">
        English Game
      </a>
    </div>
  </nav>
  <main class="equal_margin">
    <div class="space"></div>
    <img src="{% static 'word_wolf/word_wolf_none_sub.png' %}" width="150" height="150" class="equal_margin"
      alt="word wolf">
    <h3 class="text-center text-light">Enter players name</h3>
    <div class="equal_margin">
      <form action="{% url 'word_wolf:check_template' %}" method="post">
        {% csrf_token %}
        <div class="card card-top text-center equal_margin">
          <div class="card-body">
            {% for i in players_num_list %}
            <div class="input-group flex-nowrap mt-2 mb-2">
              <input type="text" class="form-control border-0 rounded-pill" placeholder="player name"
                aria-label="Username" aria-describedby="addon-wrapping" name="{{ i }}">
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="button-size2 equal_margin mt-3">
          <input class="btn btn-light rounded-pill equal_margin" type="submit" value="NEXT">
        </div>
      </form>
    </div>
  </main>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

english_games/word_wolf/templates/word_wolf/result.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- css -->
  <link rel="stylesheet" href="{% static 'word_wolf/common.css' %}">

  <!-- javascript -->
  <script src="{% static 'word_wolf/common.js' %}"></script>

  <title>英語ゲームWord Wolf</title>
</head>

<body>
  <nav class="navbar navbar-light fixed-top navbar-color">
    <div class="container-fluid">
      <a class="navbar-brand fs-3 text-light top-font" href="#">
        <img src="{% static 'word_wolf/School.png' %}" width="35" height="35" class="d-inline-block align-text-top"
          alt="word wolf">
        English Game
      </a>
    </div>
  </nav>
  <main class="equal_margin">
    <div class="space"></div>
    <img src="{% static 'word_wolf/word_wolf_none_sub.png' %}" width="150" height="150" class="equal_margin"
      alt="word wolf">
    <h2 class="text-center text-light">答え！！</h2>
    <div class="card card-top text-center equal_margin">
      <div class="card-body">
        <p>XXXさんがウルフ【YYYYY】でした</p>
        <p>XXXさんは村人【YYYYY】でした</p>
        <p>XXXさんは村人【YYYYY】でした</p>
      </div>
    </div>
    <div class="button-size2 equal_margin mt-3">
      <a class="btn btn-light rounded-pill equal_margin" href="{% url 'word_wolf:check_template' %}"
        role="button">次のお題！！</a>
    </div>
    <div class="button-size2 equal_margin mt-3">
      <a class="btn btn-light rounded-pill equal_margin" href="{% url 'word_wolf:top_template' %}"
        role="button">ジャンル変更</a>
    </div>
    <div class="button-size2 equal_margin mt-3">
      <a class="btn btn-light rounded-pill equal_margin" href="{% url 'word_wolf:top_template' %}"
        role="button">TOPへ戻る</a>
    </div>
  </main>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
</body>

</html>

english_games/word_wolf/templates/word_wolf/top.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- css -->
  <link rel="stylesheet" href="{% static 'word_wolf/common.css' %}">

  <title>英語ゲームWord Wolf</title>
</head>

<body>
  <main class="equal_margin">
    <div class="space">
      <a class="navbar-brand fs-3 text-light top-font equal_margin text_center" href="#">
        <img src="{% static 'word_wolf/School.png' %}" width="35" height="35" class="d-inline-block align-text-top"
          alt="word wolf">
        English Game
      </a>
    </div>
    <img src="{% static 'word_wolf/word_wolf_none_sub.png' %}" width="150" height="150" class="equal_margin"
      alt="word wolf">
    <div class="equal_margin">
      <form action="{% url 'word_wolf:player_template' %}" method="post">
        <div class="card card-top text-center equal_margin">
          <div class="card-body">
            {% csrf_token %}
            <div class="mt-1 mb-1">
              <h6 class="card-title top-title jp">How many players?</h6>
              <div class="button-size1 equal_margin rounded-pill bg-light">
                <button type="button" class="btn" id="playersdecreaseBtn">-</button>
                <input class="btn ms-1" value="{{ players }}" type="number" name="players" id="playersinputField"
                  style="width: 60px;" readonly>
                <button type="button" class="btn" id="playersincreaseBtn">+</button>
              </div>
            </div>
            <div class="mt-1 mb-1">
              <h6 class="card-title top-title jp">How many minority?</h6>
              <div class="button-size1 equal_margin rounded-pill bg-light">
                <button type="button" class="btn" id="minoritydecreaseBtn">-</button>
                <input class="btn ms-1" type="number" value="{{ minority }}" name="minority" id="minorityinputField"
                  style="width: 60px;" readonly>
                <button type="button" class="btn" id="minorityincreaseBtn">+</button>
              </div>
            </div>
            <div class="mt-1 mb-1">
              {% if message %}
              <h6 class="text-danger">{{ message }}</h6>
              {% else %}
              <h6 class="card-title top-title jp">Select genre</h6>
              {% endif %}
              <div class="button-size1 equal_margin rounded-pill bg-light">
                <!-- Button trigger modal -->
                <a class="btn btn-light rounded-pill genre-button orenge-button" data-bs-toggle="modal"
                  data-bs-target="#selectGenre" id="GenreLink">Select Genre</a>
                <input type="text" id="GenreInput" style="display: none;" name="genre">
              </div>
              <!-- Modal -->
              <div class="modal fade" id="selectGenre" tabindex="-1" aria-labelledby="selectGenreLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">Select genre</h5>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="container">
                        <div class="row">
                          <div class="col">
                            <button type="button" class="btn btn-light rounded-pill pink-button"
                              id="LoveBtn">Love</button>
                          </div>
                          <div class="col">
                            <button type="button" class="btn btn-light rounded-pill yellow-button"
                              id="HobbiesBtn">Hobbies</button>
                          </div>
                          <div class="col">
                            <button type="button" class="btn btn-light rounded-pill green-button"
                              id="FoodBtn">Food</button>
                          </div>
                        </div>
                      </div>
                      <div class="container mt-3">
                        <div class="row">
                          <div class="col">
                            <button type="button" class="btn btn-light rounded-pill red-ish-button"
                              id="DreamsBtn">Dreams</button>
                          </div>
                          <div class="col">
                            <button type="button" class="btn btn-light rounded-pill gray-button"
                              id="WorkBtn">Work</button>
                          </div>
                          <div class="col">
                            <button type="button" class="btn btn-light rounded-pill blue-button"
                              id="MoviesBtn">Movies</button>
                          </div>
                        </div>
                      </div>
                      <div class="container mt-3">
                        <div class="row">
                          <div class="col">
                            <button type="button" class="btn btn-light rounded-pill red-button"
                              id="EighteenBtn">18+</button>
                          </div>
                          <div class="col">
                          </div>
                          <div class="col">
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Back</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="button-size2 equal_margin mt-3">
          <input class="btn btn-light rounded-pill equal_margin orenge-button genre-button" type="submit"
            value="START!!">
        </div>
      </form>
      <div class="button-size2 equal_margin mt-3">
        <a class="btn btn-light rounded-pill equal_margin" href="{% url 'word_wolf:rule_template' %}" role="button">How
          to play</a>
      </div>
    </div>
  </main>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->

  <!-- javascript -->
  <script src="{% static 'word_wolf/scroll.js' %}"></script>
  <script src="{% static 'word_wolf/button.js' %}"></script>
  <script src="{% static 'word_wolf/modal.js' %}"></script>
</body>

</html>